// Generated by CoffeeScript 1.4.0
(function() {
  var myApp;

  myApp = angular.module("myApp", ['genericDirectives', 'teamService', 'playerService']);

  myApp.config([
    "$locationProvider", "$routeProvider", function($locationProvider, $routeProvider) {
      var base;
      $locationProvider.html5Mode(true);
      base = '/demo';
      $routeProvider.when("" + base + "/app", {
        templateUrl: "" + base + "/static/files/home.html",
        controller: "HomeCtlr"
      }).when("" + base + "/app/team", {
        templateUrl: "" + base + "/static/files/team.html",
        controller: "TeamCtlr"
      }).when("" + base + "/app/player", {
        templateUrl: "" + base + "/static/files/player.html",
        controller: "PlayerCtlr"
      }).when("" + base + "/app/directive", {
        templateUrl: "" + base + "/static/files/directive.html",
        controller: "DirectiveCtlr"
      }).otherwise({
        redirectTo: "" + base + "/app"
      });
      return true;
    }
  ]);

  myApp.controller('HomeCtlr', [
    '$scope', '$location', '$route', 'TeamService', 'PlayerService', function($scope, $location, $route, TeamService, PlayerService) {
      $scope.$location = $location;
      $scope.$route = $route;
      $scope.location = window.location;
      console.log("HomeCtlr");
      $scope.teams = TeamService.query({
        id: ""
      });
      $scope.players = PlayerService.query({
        id: ""
      });
      return true;
    }
  ]);

  myApp.controller('TeamCtlr', [
    '$scope', '$location', '$route', 'TeamService', 'PlayerService', function($scope, $location, $route, TeamService, PlayerService) {
      $scope.$location = $location;
      $scope.$route = $route;
      $scope.location = window.location;
      console.log("TeamCtlr");
      $scope.team = TeamService.get({
        id: '1'
      });
      return true;
    }
  ]);

  myApp.controller('PlayerCtlr', [
    '$scope', '$location', '$route', 'TeamService', 'PlayerService', function($scope, $location, $route, TeamService, PlayerService) {
      $scope.$location = $location;
      $scope.$route = $route;
      $scope.location = window.location;
      console.log("PlayerCtlr");
      $scope.kinds = ['good', 'bad'];
      $scope.player = PlayerService.get({
        id: '3'
      }, function(data, headers) {
        console.log("PlayerService get success");
        console.log(data);
        console.log(headers());
        console.log($scope.player);
        $scope.player.speed = 5;
        $scope.player.health = 10;
        return $scope.player.$put({}, function(data, headers) {
          console.log("PlayerService put success");
          console.log(data);
          return console.log(headers());
        }, function(response) {
          console.log("PlayerService put fail");
          console.log(response);
          return console.log(response.headers());
        });
      }, function(response) {
        console.log("PlayerService get fail");
        console.log(response);
        return console.log(response.headers());
      });
      return true;
    }
  ]);

  myApp.controller('DirectiveCtlr', [
    '$scope', '$location', '$route', 'TeamService', 'PlayerService', function($scope, $location, $route, TeamService, PlayerService) {
      $scope.$location = $location;
      $scope.$route = $route;
      $scope.location = window.location;
      console.log("DirectiveCtlr");
      return true;
    }
  ]);

}).call(this);
