// Generated by CoffeeScript 1.4.0
(function() {
  var demo;

  demo = angular.module("demo", ['myBlurFocus']);

  demo.config([
    "$locationProvider", "$routeProvider", function($locationProvider, $routeProvider) {
      var base;
      $locationProvider.html5Mode(true);
      base = '/demo';
      $routeProvider.when("" + base + "/app", {
        templateUrl: "" + base + "/static/files/home.html",
        controller: "HomeCtlr"
      }).when("" + base + "/app/home", {
        templateUrl: "" + base + "/static/files/home.html",
        controller: "HomeCtlr"
      }).otherwise({
        redirectTo: "" + base + "/app"
      });
      return true;
    }
  ]);

  demo.controller('HomeCtlr', [
    '$scope', '$location', '$route', function($scope, $location, $route) {
      $scope.$location = $location;
      $scope.$route = $route;
      $scope.location = window.location;
      $scope.test = "hello world";
      $scope.doMyBlur = function($event) {
        return $scope.test = $scope.burp;
      };
      $scope.doMyFocus = function($event) {
        return $scope.test = $scope.burp;
      };
      console.log("HomeCtlr");
      return true;
    }
  ]);

}).call(this);
