// Generated by CoffeeScript 1.4.0
(function() {

  angular.module("genericDirectives", []).directive('myBlur', [
    '$parse', function($parse) {
      var link;
      link = function($scope, elm, attrs) {
        var fn;
        fn = $parse(attrs.myBlur);
        elm.bind('blur', function(event) {
          return $scope.$apply(function() {
            return fn($scope, {
              $event: event
            });
          });
        });
        return true;
      };
      return link;
    }
  ]).directive('myFocus', [
    '$parse', function($parse) {
      var link;
      link = function($scope, elm, attrs) {
        var fn;
        fn = $parse(attrs.myFocus);
        elm.bind('focus', function(event) {
          return $scope.$apply(function() {
            return fn($scope, {
              $event: event
            });
          });
        });
        return true;
      };
      return link;
    }
  ]).directive('contenteditable', function() {
    var ddo;
    ddo = {
      restrict: 'A',
      require: '?ngModel',
      link: function($scope, elm, attrs, ngModel) {
        var read;
        if (!ngModel) {
          return;
        }
        read = function() {
          return ngModel.$setViewValue(elm.html());
        };
        read();
        ngModel.$render = function() {
          return elm.html(ngModel.$viewValue || '');
        };
        return elm.bind('blur keyup change', function() {
          return $scope.$apply(read);
        });
      }
    };
    return ddo;
  });

}).call(this);
